name: 'dbt_benchmark'
version: '1.0.0'
profile: 'dbt_benchmark'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_benchmark:
    staging:
      +schema: staging
      +materialized: table
    intermediate:
      +schema: intermediate
      +materialized: table
    marts:
      +schema: mart
      +materialized: table
